/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  stellarSidebar: [
    {
      type: 'category',
      label: 'Stellar',
      items: ['root', 'code-noobs-archive/Introduction to Programming', 'code-noobs-archive/Introduction to DOM', 'code-noobs-archive/Functions'],
    },
  ]}

export default sidebars;
